### ISSUE TITLE
VuePress 折腾记 | Ceil.Top

### ISSUE THREAD

**Issue by kevinsheep** [kevinsheep/blog#19]
https://ceil.top/FE/vuepress-play-around.html 

 Blog Of KEVINSHEEP

**Comment by alternativedestiny** [comment]
大佬，我再自己写添加sidebar的时候总是出现这样的问题，请问有什么解决方法吗

```py
const fs = require('fs');

function getSideBar() {
    let file_list = fs.readdirSync('../pages/Python/');
    console.log(file_list);
    for (let i = 0; i < file_list.length; i++) {
        file_list[i] = file_list[i].slice(0, -3)
    }
    return file_list;
}
```

```bash
Error: ENOENT: no such file or directory, scandir '../pages/Python/'
    at Object.readdirSync (fs.js:854:3)
    at getSideBar (D:\PersonalProject\vue_press\docs\.vuepress\config.js:4:24)
    at Object.<anonymous> (D:\PersonalProject\vue_press\docs\.vuepress\config.js:115:31)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfig (D:\PersonalProject\vue_press\node_modules\_@vuepress_core@1.5.2@@vuepress\core\lib\node\loadConfig.js:31:18)
    at App.resolveConfigAndInitialize (D:\PersonalProject\vue_press\node_modules\_@vuepress_core@1.5.2@@vuepress\core\lib\node\App.js:64:24)
    at App.process (D:\PersonalProject\vue_press\node_modules\_@vuepress_core@1.5.2@@vuepress\core\lib\node\App.js:103:16)
    at dev (D:\PersonalProject\vue_press\node_modules\_@vuepress_core@1.5.2@@vuepress\core\lib\index.js:17:13)
    at D:\PersonalProject\vue_press\node_modules\_vuepress@1.5.2@vuepress\lib\util.js:35:12
    at CAC.<anonymous> (D:\PersonalProject\vue_press\node_modules\_vuepress@1.5.2@vuepress\lib\registerCoreCommands.js:38:23)
    at CAC.runMatchedCommand (D:\PersonalProject\vue_press\node_modules\_cac@6.5.10@cac\dist\index.js:591:34)
```

**Comment by SaulJWu** [comment]
学习了，他这个是自动检测markdown文件变动吗？每次往里面扔md文件就自动部署了？还是要手动运行脚本？

**Comment by kevinsheep** [comment]
> 学习了，他这个是自动检测markdown文件变动吗？每次往里面扔md文件就自动部署了？还是要手动运行脚本？
开发环境下，是更新md文件就能在本地看到效果。
要发布，还是要执行脚本的，如果是更新到BLOG还要上传一下。当然，你可以写成脚本，减少手动操作。

**Comment by SaulJWu** [comment]
> > 学习了，他这个是自动检测markdown文件变动吗？每次往里面扔md文件就自动部署了？还是要手动运行脚本？
> 
> 开发环境下，是更新md文件就能在本地看到效果。
> 要发布，还是要执行脚本的，如果是更新到BLOG还要上传一下。当然，你可以写成脚本，减少手动操作。

我也折腾完了，我们来建立友情链接吧~~~
https://sauljwu.github.io/
